name: Bug Report
description: Report a bug in gaji
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: input
    id: version
    attributes:
      label: gaji version
      description: "Run `gaji --version` and paste the output."
      placeholder: "0.2.7"
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - npm (npx gaji)
        - cargo install
        - Binary download
        - Built from source
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages or screenshots if applicable.
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow file (if applicable)
      description: Paste your TypeScript workflow file if relevant.
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem.
