pub const GAJI_SCRIPTS: &[(&str, &str)] = &[
    ("gha:dev", "gaji dev"),
    ("gha:build", "gaji build"),
    ("gha:watch", "gaji dev --watch"),
];

pub const GAJI_DEV_DEPS: &[(&str, &str)] = &[("tsx", "^4.0.0")];

pub const TSCONFIG_TEMPLATE: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "moduleResolution": "bundler",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["workflows/**/*"],
  "exclude": ["node_modules", "dist"]
}
"#;

pub const EXAMPLE_WORKFLOW_TEMPLATE: &str = r#"// Example CI workflow - Generated by gaji init
import { getAction, Job, Workflow } from "../generated/index.js";

const checkout = getAction("actions/checkout@v5");
const setupNode = getAction("actions/setup-node@v4");

new Workflow({
    name: "CI",
    on: {
        push: {
            branches: ["main"],
        },
        pull_request: {
            branches: ["main"],
        },
    },
}).jobs(j => j
    .add("build",
        new Job("ubuntu-latest")
            .steps(s => s
                .add(checkout({ name: "Checkout code" }))
                .add(setupNode({
                    name: "Setup Node.js",
                    with: { "node-version": "20" },
                }))
                .add({ name: "Install dependencies", run: "npm ci" })
                .add({ name: "Run tests", run: "npm test" })
            )
    )
).build("ci");
"#;

pub const GAJI_CONFIG_TEMPLATE: &str = r#"import { defineConfig } from "./generated/index.js";

export default defineConfig({
    workflows: "workflows",
    output: ".github",
    generated: "generated",
});
"#;

pub const GITIGNORE_SECTION: &str =
    "\n# gaji generated files\ngenerated/\n.gaji-cache.json\ngaji.config.local.ts\n";
